### ISSUE TITLE
Fix Kafka Logs [ParticipationSystem] [Dashboard]

### ISSUE THREAD

**Issue by gdelacruzfdez** [Arquisoft/parti_i3b#1]
* In the kafka logs, add the ID of the proposal/comments in order to know the one who has recieved the updates

* Standarize the kafka logs between both modules

**Comment by juanfpo96** [comment]
Final format:

New proposal
New comment
Upvoted comment: [id]
Upvoted proposal: [id]
Downvoted comment: [id]
Downvoted proposal: [id]
